# Generated by Django 4.2.2 on 2023-06-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("微信号", models.CharField(max_length=100)),
                ("姓名", models.CharField(max_length=40)),
                ("number", models.IntegerField()),
            ],
        ),
    ]
