# Generated by Django 4.2.2 on 2023-06-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="number",
            new_name="数字",
        ),
    ]
