# Generated by Django 4.2.2 on 2023-06-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0002_rename_number_history_数字"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="年级",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="班级",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
