# Generated by Django 4.2.2 on 2023-06-09 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainsite", "0003_history_年级_history_班级"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="姓名",
        ),
        migrations.AddField(
            model_name="history",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
