# Generated by Django 4.2.2 on 2023-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0004_remove_history_姓名_history_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
