# Generated by Django 4.2.2 on 2023-06-09 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainsite", "0006_number_in_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Winners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("微信号", models.CharField(max_length=100)),
                ("数字", models.IntegerField()),
                ("年级", models.PositiveSmallIntegerField()),
                ("班级", models.PositiveSmallIntegerField()),
                ("delta", models.PositiveSmallIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
