# Generated by Django 4.2.2 on 2023-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0007_winners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="数字",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="winners",
            name="数字",
            field=models.FloatField(),
        ),
    ]
