# Generated by Django 4.2.2 on 2023-06-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0009_alter_number_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="班级",
            new_name="class_number",
        ),
        migrations.RenameField(
            model_name="history",
            old_name="年级",
            new_name="grade",
        ),
        migrations.RenameField(
            model_name="history",
            old_name="数字",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="history",
            old_name="微信号",
            new_name="wechat_id",
        ),
        migrations.RenameField(
            model_name="winners",
            old_name="班级",
            new_name="class_number",
        ),
        migrations.RenameField(
            model_name="winners",
            old_name="年级",
            new_name="grade",
        ),
        migrations.RenameField(
            model_name="winners",
            old_name="数字",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="winners",
            old_name="微信号",
            new_name="wechat_id",
        ),
    ]
