# Generated by Django 4.2.2 on 2023-06-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0010_rename_班级_history_class_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="history",
            name="wechat_id",
        ),
        migrations.RemoveField(
            model_name="winners",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="winners",
            name="wechat_id",
        ),
    ]
