# Generated by Django 4.2.2 on 2023-06-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0011_remove_history_grade_remove_history_wechat_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="class_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="winners",
            name="class_number",
            field=models.CharField(max_length=10),
        ),
    ]
