# Generated by Django 4.2.2 on 2023-06-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainsite", "0012_alter_history_class_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winners",
            name="delta",
            field=models.FloatField(),
        ),
    ]
