# Generated by Django 4.2.2 on 2023-06-11 23:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainsite", "0014_boomed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Boomed",
            new_name="Bombed",
        ),
    ]
